name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

permissions:
  contents: read #  to fetch code (actions/checkout)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Build with Maven
      run: mvn clean install

  
    - name: Build and verify
      run: ./mvnw verify javadoc:javadoc site:site --batch-mode --errors --settings .github/workflows/settings.xml
    - name: Run unit tests and generate coverage report
      run: mvn test jacoco:report

    - name: SonarQube Scan
      run: mvn sonar:sonar -Dsonar.projectKey=code-coverage -Dsonar.host.url=http://3.88.181.110:9000 -Dsonar.login=sqp_da3a3d6e6d231009b71dcd6de84487ee944072a4

  publish-snapshots:
    name: Publish snapshot artifacts
    if: github.event_name == 'push' && github.repository == 'junit-team/junit4' && github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download Maven # Download with default JDK because OpenJDK 6 does not support TLS 1.2
        run: ./mvnw --version
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 8
      # - name: Publish snapshot artifacts
      #   env:
      #     OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
      #     OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
      #   run: ./mvnw deploy --batch-mode --errors --activate-profiles generate-docs --settings .github/workflows/settings.xml
